Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
     config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
        vb.name = "suresh - docker"
     end 
     config.vm.provision "docker" do |d|
         d.pull_images "rabbitmq"
         d.run "rabbitmq"
      end
 end